### ISSUE TITLE
Preprocessing module 

### ISSUE THREAD

**Issue by M0hammadL** [theislab/pertpy#12]
The ECCITE-seq data consists of transcriptomics and surface protein data. Both types of data require quality control and preprocessing to ensure that the data is ready for downstream tasks.

**- QC and normalization of transcriptomics data:**
We don't need to do much just similar prep from Scanpy. Basically, we just need to ensure that our example notebook has a quick run down of scRNA-seq QC and normalization.

**- QC and normalization of protein data:**
- [x] QC is still open, but @Zethson is looking into it. Maybe adapt from https://scanpy-tutorials.readthedocs.io/en/latest/cite-seq/pbmc5k.html
- [x]  CLR (centered log-ratio transformation) similar to mixescape
- [x] LogNormalize also in mixscape
- [x] Relative counts also in miix scape (https://satijalab.org/seurat/reference/normalizedata)
- [x] Advanced method: Denoised and Scaled by Background (DSB) the method is in R but works with seurat object (https://www.biorxiv.org/content/10.1101/2020.02.24.963603v1.full.pdf) and code here (https://github.com/niaid/dsb)

**Comment by Zethson** [comment]
https://muon.readthedocs.io/en/latest/omics/citeseq.html

already seems to offer some normalization.
