### ISSUE TITLE
Implement scikit-learn-intelex for random forest and logistic regression

### ISSUE THREAD

**Issue by antschum** [theislab/pertpy#139]
The intelex patch could make the random forest and logistic regression computations several times faster. 

For reference: https://github.com/intel/scikit-learn-intelex

Example implementation: 
https://github.com/theislab/ehrapy/blob/development/ehrapy/preprocessing/_data_imputation.py#L217

**Comment by Zethson** [comment]
It's gotten a bit unreliable and I'll put this into the backlog.
