### ISSUE TITLE
Cell-type composition analysis 

### ISSUE THREAD

**Issue by M0hammadL** [theislab/pertpy#14]
### compostion analysis 

We need to have a function like` perp.composition(adata, method, cell_type:...)`. I have already talked to Beni, it seems [scCODA](https://github.com/theislab/scCODA/tree/update_0.1.3) already has good wrappers for statistical methods (some in R but they have wrapper for them) and has already 12 test statistics implemented 

We need to include them in here and for some of them reimplement (fastest ones). 

For now, we can use the ones that are already there to reimplement stuff we have to talk to Johannes who maintains them.

**Comment by Zethson** [comment]
@MO-L which ones do you want to be reimplemented for what reason? Because they are R wrappers and slow?

**Comment by Zethson** [comment]
Now tracked in #165  #169
