### ISSUE TITLE
Add Distances

### ISSUE THREAD

**Issue by Zethson** [theislab/pertpy#178]
**Distances to implement**
- E-distance
- MMD
- Wasserstein distance 
- Pseudobulk distance (distances b/w centroids)

**Tests to implement**
- E-test [[ general distance-based permutation test ]] 

Implementation plan
- [x] Read https://pertpy.readthedocs.io/en/latest/contributing.html
- [x] Browse around https://github.com/theislab/pertpy
- [x] Add `_distances.py` to tools in pertpy
- [x] Draft an API for a new Distance class in the above mentioned file
- [x] Create function stubs with associated docstrings -> open a PR and ping @Zethson who'll happily discuss this with you
- [x] Implement the distance functions. 
- [x] Write test functions in the test module in pertpy with artificially (in memory) created AnnData objects. These tests should be as fast as possible. You'll notice that some of pertpy's current tests are slow AF which will be improved in the future (and is bad).
- [x] Add your Distance class with some text in /docs/usage/usage.md
- [x] Write a notebook tutorial and create a PR to https://github.com/theislab/pertpy-tutorials/
- [x] Ping @Zethson who'll review everything until it's in a good state
- [x] Celebrate, because this will get used a lot and you'll have impact on the field

**Comment by stefanpeidli** [comment]
Currently, test_*.py are downloading data. Not as slow as the other test modules, but still improvable.
