### ISSUE TITLE
Datasets 

### ISSUE THREAD

**Issue by M0hammadL** [theislab/pertpy#18]
We have multiple datasets that we need to prepare:

# multimodal single-cell CRISPR screens: 

- [ ]  https://nature.com/articles/s41588-021-00779-1 

- [ ]  https://www.nature.com/articles/s41588-021-00778-2 (mixscape)

- [ ] Christians Bocks dataset (we already have it) 

- [ ]  Hanifta large scale cite-se datasets with covid 19 (Chris has the data, large-scale CITE-seq, maybe goo to show scale)

# Uni Modal KO datasets #17 

- [ ]  Norman et al.  https://science.sciencemag.org/content/365/6455/786.abstract (we have)

# Normal scRNA-seq:

- continues covariates to test auger ( https://science.sciencemag.org/content/367/6473/45, we have the data)
- cross-species dataset with continuous-time but only perturbation (https://www.nature.com/articles/s41586-018-0657-2, we have the data)

# RNA velocity perturbation analysis  

- [x] dataset which was analyzed augor protocol paper

**Comment by ilibarra** [comment]
- [ ] Prepare the mixscape toy dataset and upload it into a function to the pertpy.datasets equivalent. (me)

**Comment by Zethson** [comment]
Tracked in some GDoc
