### ISSUE TITLE
Link to documentation is outdated

### ISSUE THREAD

**Issue by VladimirShitov** [theislab/pertpy#191]
The link to the usage in readme doesn't work. If this issue is not closed in one of the PRs, I suggest changing it from 
https://pertpy.readthedocs.io/en/latest/usage.html
to 
https://pertpy.readthedocs.io/en/latest/usage/usage.html

**Comment by Zethson** [comment]
Thank you! https://github.com/theislab/pertpy/commit/182b31c402f42df6ac92a9e49a87898b6921c73b
