### ISSUE TITLE
Reversed labele

### ISSUE THREAD

**Issue by tshiihashi** [theislab/pertpy#192]
Thank you for opening the script!
I used the following jupyter-notebook as a reference to filter my data at hand and enter the following command:
https://github.com/theislab/pertpy-tutorials/blob/main/mixscape.ipynb
`mixscape_identifier = pt.tl.Mixscape()`
`mixscape_identifier.pert_sign(adata, 'perturbation', 'NT')`
`mixscape_identifier.mixscape(adata = adata, control = 'NT', labels='grna')`
I got the mislabeling result that KO labels were reversed in some gRNAs (see RPL11, LDB1).
![image](https://user-images.githubusercontent.com/104621764/215318032-4aa9585c-4466-4254-a277-95a8611267e1.png)
![image](https://user-images.githubusercontent.com/104621764/215318432-4cbef0c4-93c3-4b39-b560-4fac1fb2b138.png)
![image](https://user-images.githubusercontent.com/104621764/215318043-99b909b6-3cb0-4e1a-b985-cb9ae9d39088.png)

Since RACK1 is labeled correctly, I do not believe it is an alphabetical issue.
I am wondering if this result is due to the labeling of KO on the higher cell number of gRNA-transfected cells.
Could you please tell us why this is happening?

**Comment by Zethson** [comment]
Thanks, we'll look into it!

**Comment by xinyuejohn** [comment]
> Thank you for opening the script! I used the following jupyter-notebook as a reference to filter my data at hand and enter the following command: [theislab/pertpy-tutorials@`main`/mixscape.ipynb](https://github.com/theislab/pertpy-tutorials/blob/main/mixscape.ipynb?rgh-link-date=2023-01-29T10%3A29%3A05Z) `mixscape_identifier = pt.tl.Mixscape()` `mixscape_identifier.pert_sign(adata, 'perturbation', 'NT')` `mixscape_identifier.mixscape(adata = adata, control = 'NT', labels='grna')` 
> Since RACK1 is labeled correctly, I do not believe it is an alphabetical issue. I am wondering if this result is due to the labeling of KO on the higher cell number of gRNA-transfected cells. Could you please tell us why this is happening?

Hi, thanks for your feedback! Could you please add `layer='X_pert'` to your mixscape function and try again? 
i.e. `mixscape_identifier.mixscape(adata = adata, control = 'NT', labels='grna', layer='X_pert')`

Because by default, pert_sign will write the perturbation signature directly to .layers[“X_pert”] of the provided adata. And mixscape will use .X by default. And in your case, mixscape still uses the original .X data.

Hope this will solve your issue!

**Comment by xinyuejohn** [comment]
@Zethson I think the data pipeline could be improved. Becasue by default pert_sign writes results into .layers[“X_pert”]  and mixscape uses .X by default. Should I change it so that mixscape will use .layers[“X_pert”] by default?

**Comment by Zethson** [comment]
Yeah, that makes sense. Please yes.

**Comment by tshiihashi** [comment]
Thank you very much!
Problem solved!
