### ISSUE TITLE
Not compatible with latest Python 3.10+

### ISSUE THREAD

**Issue by nroak** [theislab/pertpy#213]
### Report

Is it possible to install with version compatible with latest python? Otherwise it's hard to work with updated pacakges like scvi-tools that require python >3.10.
```
> pip install pertpy
ERROR: Ignored the following versions that require a different python version: 0.1.0 Requires-Python >=3.8.0,<3.10; 0.2.0 Requires-Python >=3.8.0,<3.10; 0.3.0 Requires-Python >=3.8.0,<3.10
ERROR: Could not find a version that satisfies the requirement pertpy (from versions: none)
ERROR: No matching distribution found for pertpy

```

**Comment by Zethson** [comment]
We've already addressed this and you will be able to install it with Python 3.10 with the next release! In the meantime you can install pertpy from the development branch. 

```
pip install git+https://github.com/theislab/pertpy.git@development
```

should do the trick if I recall correctly. Sorry for the inconvenience until then!

**Comment by nroak** [comment]
Thank you very much!
