### ISSUE TITLE
TypeError: arguments did not match any overloaded call and QImage(variant: Any): too many arguments

### ISSUE THREAD

**Issue by nroak** [theislab/pertpy#214]
### Report

I'm running the composition analysis per [the tutorial ](https://www.sc-best-practices.org/conditions/compositional.html#with-labeled-clusters-and-hierarchical-structure) and encountering an error at the tree generation step as below:

```
> tasccoda_model = pt.tl.Tasccoda()
> tasccoda_data = tasccoda_model.load(
    adata,
    type="cell_level",
    cell_type_identifier="nsbm_level_1",
    sample_identifier=batch_key,
    covariate_obs=["genotype"],
    levels_orig=["nsbm_level_4", "nsbm_level_3", "nsbm_level_2", "nsbm_level_1"],
    add_level_name=True,
)
> tasccoda_data

MuData object with n_obs × n_vars = 23039 × 18297
  var:	'n_cells'
  2 modalities
    rna:	23034 x 18227
      obs:	'genotype', 'replicate', 'batch', 'scDblFinder_class', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_20_genes', 'total_counts_mt', 'log1p_total_counts_mt', 'pct_counts_mt', 'total_counts_ribo', 'log1p_total_counts_ribo', 'pct_counts_ribo', 'total_counts_hb', 'log1p_total_counts_hb', 'pct_counts_hb', 'outlier', 'mt_outlier', 'size_factors', 'leiden', 'leiden_res0_25', 'leiden_res0_5', 'leiden_res1', 'S_score', 'G2M_score', 'phase', 'manual_celltype_annotation', 'gt_rep', 'scCODA_sample_id', 'nsbm_level_0', 'nsbm_level_1', 'nsbm_level_2', 'nsbm_level_3', 'nsbm_level_4', 'nsbm_level_5', 'nsbm_level_6'
      var:	'gene_ids', 'feature_types', 'genome', 'mt', 'ribo', 'hb', 'n_cells_by_counts', 'mean_counts', 'log1p_mean_counts', 'pct_dropout_by_counts', 'total_counts', 'log1p_total_counts', 'n_cells', 'highly_deviant', 'highly_variable', 'means', 'dispersions', 'dispersions_norm', 'highly_variable_nbatches', 'highly_variable_intersection'
      uns:	'genotype_colors', 'gt_rep_colors', 'hvg', 'leiden', 'leiden_res0_25_colors', 'leiden_res0_5_colors', 'leiden_res1_colors', 'manual_celltype_annotation_colors', 'neighbors', 'pca', 'phase_colors', 'replicate_colors', 'tsne', 'umap', 'schist', 'nsbm_level_1_colors', 'nsbm_level_2_colors'
      obsm:	'X_pca', 'X_tsne', 'X_umap', 'CM_nsbm_level_0', 'CM_nsbm_level_1', 'CM_nsbm_level_2', 'CM_nsbm_level_3', 'CM_nsbm_level_4', 'CM_nsbm_level_5', 'CM_nsbm_level_6'
      varm:	'PCs'
      layers:	'PFlog1pPF_normalization', 'counts', 'log1pPF_normalization', 'raw_counts', 'scTransform_normalization', 'scran_normalization', 'soupX_counts'
      obsp:	'connectivities', 'distances'
    coda:	5 x 70
      obs:	'genotype', 'gt_rep'
      var:	'n_cells'
      uns:	'tree'

> pt.pl.coda.draw_tree(tasccoda_data)

File ~/opt/anaconda3/envs/scanpy/lib/python3.10/site-packages/ete3/coretype/tree.py:1392, in TreeNode.render(self, file_name, layout, w, h, tree_style, units, dpi)
   1388     return drawer.get_img(self, w=w, h=h,
   1389                           layout=layout, tree_style=tree_style,
   1390                           units=units, dpi=dpi, return_format=file_name)
   1391 else:
-> 1392     return drawer.render_tree(self, file_name, w=w, h=h,
   1393                             layout=layout, tree_style=tree_style,
   1394                               units=units, dpi=dpi)

File ~/opt/anaconda3/envs/scanpy/lib/python3.10/site-packages/ete3/treeview/drawer.py:111, in render_tree(t, imgName, w, h, layout, tree_style, header, units, dpi)
    109 scene.addItem(scene.master_item)
    110 if imgName.startswith("%%inline"):
--> 111     imgmap = save(scene, imgName, w=w, h=h, units=units, dpi=dpi)
    112 else:
    113     x_scale, y_scale = save(scene, imgName, w=w, h=h, units=units, dpi=dpi)

File ~/opt/anaconda3/envs/scanpy/lib/python3.10/site-packages/ete3/treeview/main.py:752, in save(scene, imgName, w, h, dpi, take_region, units)
    750 else:
    751     targetRect = QRectF(0, 0, w, h)
--> 752     ii= QImage(w, h, QImage.Format_ARGB32)
    753     ii.fill(QColor(Qt.white).rgb())
    754     ii.setDotsPerMeterX(dpi / 0.0254) # Convert inches to meters

TypeError: arguments did not match any overloaded call:
  QImage(): too many arguments
  QImage(size: QSize, format: QImage.Format): argument 1 has unexpected type 'float'
  QImage(width: int, height: int, format: QImage.Format): argument 1 has unexpected type 'float'
  QImage(data: bytes, width: int, height: int, format: QImage.Format): argument 1 has unexpected type 'float'
  QImage(data: PyQt5.sip.voidptr, width: int, height: int, format: QImage.Format): argument 1 has unexpected type 'float'
  QImage(data: bytes, width: int, height: int, bytesPerLine: int, format: QImage.Format): argument 1 has unexpected type 'float'
  QImage(data: PyQt5.sip.voidptr, width: int, height: int, bytesPerLine: int, format: QImage.Format): argument 1 has unexpected type 'float'
  QImage(xpm: List[str]): argument 1 has unexpected type 'float'
  QImage(fileName: str, format: typing.Optional[str] = None): argument 1 has unexpected type 'float'
  QImage(a0: QImage): argument 1 has unexpected type 'float'
  QImage(variant: Any): too many arguments
```

Can you please guide me how to fix this?

### Version information

-----
altair              4.2.2
anndata             0.8.0
matplotlib          3.7.0
mudata              0.2.1
numpy               1.23.5
pandas              1.5.3
pertpy              0.4.0
scanpy              1.9.2
schist              v0.7.15
seaborn             0.12.2
session_info        1.0.0
tensorflow          2.11.0
-----
PIL                                         9.4.0
PyQt5                                       NA
aa8f2297d25b4dc6fd3d98411eb3ba53823c4f42    NA
absl                                        NA
adjustText                                  NA
anyio                                       NA
appnope                                     0.1.3
arrow                                       1.2.3
arviz                                       0.14.0
asttokens                                   NA
astunparse                                  1.6.3
attr                                        22.2.0
babel                                       2.12.1
backcall                                    0.2.0
beta_ufunc                                  NA
binom_ufunc                                 NA
cairo                                       1.23.0
certifi                                     2022.12.07
cffi                                        1.15.1
cftime                                      1.6.2
charset_normalizer                          3.0.1
colorama                                    0.4.6
comm                                        0.1.2
custom_inherit                              2.4.1
cycler                                      0.10.0
cython_runtime                              NA
dateutil                                    2.8.2
debugpy                                     1.6.6
decorator                                   5.1.1
decoupler                                   1.3.4
defusedxml                                  0.7.1
dot_parser                                  NA
entrypoints                                 0.4
ete3                                        3.1.2
etils                                       1.0.0
executing                                   1.2.0
fastjsonschema                              NA
flatbuffers                                 23.1.21
fontTools                                   4.38.0
fqdn                                        NA
fsspec                                      2023.1.0
gast                                        NA
google                                      NA
graph_tool                                  2.46 (commit , )
h5py                                        3.7.0
hypergeom_ufunc                             NA
idna                                        3.4
igraph                                      0.10.4
ipykernel                                   6.21.2
ipython_genutils                            0.2.0
ipywidgets                                  8.0.4
isoduration                                 NA
jax                                         0.4.4
jaxlib                                      0.4.4
jedi                                        0.18.2
jinja2                                      3.1.2
joblib                                      1.2.0
json5                                       NA
jsonpointer                                 2.3
jsonschema                                  4.17.3
jupyter_server                              1.23.6
jupyterlab_server                           2.19.0
keras                                       2.11.0
kiwisolver                                  1.4.4
leidenalg                                   0.9.1
llvmlite                                    0.39.1
louvain                                     0.8.0
markupsafe                                  2.1.2
matplotlib_inline                           0.1.6
mizani                                      0.8.1
mpl_toolkits                                NA
multipledispatch                            0.6.0
muon                                        0.1.3
natsort                                     8.3.0
nbformat                                    5.7.3
nbinom_ufunc                                NA
ncf_ufunc                                   NA
netCDF4                                     1.6.2
numba                                       0.56.4
numpyro                                     0.10.1
opt_einsum                                  v3.3.0
packaging                                   23.0
palettable                                  3.3.0
parso                                       0.8.3
patsy                                       0.5.3
pexpect                                     4.8.0
pickleshare                                 0.7.5
pkg_resources                               NA
platformdirs                                3.0.0
plotnine                                    0.10.1
ply                                         3.11
png                                         0.20220715.0
prometheus_client                           NA
prompt_toolkit                              3.0.38
psutil                                      5.9.4
ptyprocess                                  0.7.0
pure_eval                                   0.2.2
pvectorc                                    NA
pycparser                                   2.21
pydev_ipython                               NA
pydevconsole                                NA
pydevd                                      2.9.5
pydevd_file_utils                           NA
pydevd_plugins                              NA
pydevd_tracing                              NA
pydot                                       1.4.2
pygments                                    2.14.0
pynndescent                                 0.5.8
pyomo                                       6.5.0
pyparsing                                   3.0.9
pypi_latest                                 0.1.2
pyrsistent                                  NA
pytz                                        2022.7.1
pytz_deprecation_shim                       NA
questionary                                 1.10.0
reportlab                                   3.6.12
requests                                    2.28.2
rfc3339_validator                           0.1.4
rfc3986_validator                           0.1.1
rich                                        NA
rpy2                                        3.5.9
scipy                                       1.9.3
send2trash                                  NA
setuptools                                  65.6.3
sip                                         NA
six                                         1.16.0
sklearn                                     1.2.1
skmisc                                      0.1.4
sniffio                                     1.3.0
sparsecca                                   0.3.0
stack_data                                  0.6.2
statannotations                             0.5.0
statsmodels                                 0.13.5
switchlang                                  0.1.0
tensorboard                                 2.11.2
termcolor                                   NA
terminado                                   0.17.1
texttable                                   1.6.7
threadpoolctl                               3.1.0
toolz                                       0.12.0
tornado                                     6.2
toyplot                                     1.0.3
toytree                                     2.0.1
tqdm                                        4.64.1
traitlets                                   5.9.0
typing_extensions                           NA
tzlocal                                     NA
umap                                        0.5.3
uri_template                                NA
urllib3                                     1.26.14
wcwidth                                     0.2.6
webcolors                                   1.11.1
websocket                                   1.5.1
wrapt                                       1.15.0
xarray                                      2023.2.0
xarray_einstats                             0.5.1
yaml                                        6.0
zmq                                         25.0.0
zoneinfo                                    NA
zstandard                                   0.19.0
-----
IPython             8.11.0
jupyter_client      7.4.1
jupyter_core        5.2.0
jupyterlab          3.6.1
notebook            6.5.2
-----
Python 3.10.9 (main, Jan 11 2023, 09:18:20) [Clang 14.0.6 ]
macOS-10.16-x86_64-i386-64bit
-----
Session information updated at 2023-03-01 21:14

**Comment by johannesostner** [comment]
Hi @nroak!
It seems like this issue is related to [this one](https://github.com/etetoolkit/ete/issues/635). Could you try reinstalling pyqt5 with version 5.9.7 (`pip install 'pyqt5==5.9.7' --force-reinstall`) and run the tutorial again?

**Comment by Zethson** [comment]
Closing. Please reopen if you still run into this issue.
