### ISSUE TITLE
AttributeError: module 'pertpy.tools' has no attribute 'Milopy'

### ISSUE THREAD

**Issue by nroak** [theislab/pertpy#215]
### Report

I installed the latest version of pertpy from GitHub pull but getting an error at the step below:

```
> milo = pt.tl.Milopy()
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[47], line 1
----> 1 milo = pt.tl.Milopy()

AttributeError: module 'pertpy.tools' has no attribute 'Milopy'

```
However this works- 
`> milo = pt.tl.Milo()`

The tutorial needs to be updated.

**Comment by Zethson** [comment]
We renamed Milopy to just Milo. Sorry, this would be documented with the next release.
