### ISSUE TITLE
Import problem with poetry install

### ISSUE THREAD

**Issue by tessadgreen** [theislab/pertpy#220]
### Report

Bug is occurring on server and on my laptop (M1). Both use conda. Python version 3.10.6. 

I create a new environment following the directions in the contributor guide. poetry install doesn't install pyomo, so I get an error when running `poetry run pertpy` from that, then conda install pyomo, run `poetry install` again, which seems like it works, and then when I try to actually import and use the package I get:

``

`Installed version 0.4.0 of pertpy is newer than the latest release 0.3.0! You are
running a nightly version and features may break!
ryp2 is not installed. Install with pip install rpy2 to run tools with R support.
To use sccoda or tasccoda please install ete3 with pip install ete3
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/n/groups/marks/software/anaconda_o2/envs/pertpy-dev/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'pertpy.__main__'`

I tried installing from github via pip, which will load into python but won't let me run nox without erroring ("  The Poetry configuration is invalid" error when running tests or attempting make poetry install again

**Comment by Zethson** [comment]
I've seen this before and have no idea why it's happening. Think it could be circumvented by installing it with pip instead of poetry

-->

instead of
```
poetry install
```

```
pip install .
```

I'll try to see whether I can find something. This is not good.

**Comment by Zethson** [comment]
I'll replace the `make install` command with `pip install` which should not require Poetry
