### ISSUE TITLE
Error with multiple covariates using pertypy.tl.Sccoda()

### ISSUE THREAD

**Issue by schroeme** [theislab/pertpy#224]
### Report

I am trying to using code from the ["Compositional Analysis" tutorial from Single Cell Best Practices](https://www.sc-best-practices.org/conditions/compositional.html#with-labeled-clusters) to analyze compositional differences in cell types along two dimensions (two covariates). When I run `sccoda_model.load()` using my two covariates ('age' and 'region', see below):

`sccoda_model = pt.tl.Sccoda()
sccoda_data = sccoda_model.load(
    adata,
    type="cell_level",
    generate_sample_level=True,
    cell_type_identifier="cell_type",
    sample_identifier="replicate",
    covariate_obs=["age","region"],
)`

I get the following error:

"Covariate region has non-unique values! Skipping...". However, the categories in "region" are unique. The same results when I run the above with "region" as the sole covariate, but not when I run with "age" as the sole covariate. Both are categorical types in pandas series. Any ideas on the source of this issue would be greatly appreciated, thanks!

**Comment by johannesostner** [comment]
Hi @schroeme,
the message `"Covariate region has non-unique values! Skipping..."` refers to the uniqueness of your `region` column with respect to the sample_identifier `replicate`. There seem to be cells from different regions in your data that have the same value for `replicate`. On the other hand, `age` seems to be different for every replicate.
If you want to group your data by replicate and region, you can pass them as a list to `sample_identifier`.

**Comment by johannesostner** [comment]
Unfortunately, we don't support plotting with 2 or more covariates yet. We can keep this suggestion in mind for potential future updates, though!

**Comment by kvshams** [comment]
I am facing the same issue. I am not sure what I am missing here as you can see the cell numbers are different between the Samples and phase. They are also diffrent between the Celltype_annotation.  
```
sccoda_model = pt.tl.Sccoda()
sccoda_data = sccoda_model.load(adata,
                                type="cell_level", generate_sample_level=True,
                                cell_type_identifier="Celltype_annotation",
                                sample_identifier = "Sample",
                                covariate_obs=["phase"])
```
```
Covariate phase has non-unique values! Skipping...
```
```
adata.obs['Sample_phase'].value_counts()
HT4_G2M    2656
HT1_G2M    2291
HT2_G2M    2230
HT4_G1     1531
HT2_G1     1496
HT1_G1     1465
HT4_S      1059
HT2_S      1028
HT1_S       937
```
As you suggested here, it works well with `sample_identifier` as `phase` and without any covariate. Is there any workaround to this problem for including the Sample layer into the formula?
> Hi @schroeme, the message `"Covariate region has non-unique values! Skipping..."` refers to the uniqueness of your `region` column with respect to the sample_identifier `replicate`. There seem to be cells from different regions in your data that have the same value for `replicate`. On the other hand, `age` seems to be different for every replicate. If you want to group your data by replicate and region, you can pass them as a list to `sample_identifier`.

**Comment by johannesostner** [comment]
Hi @kvshams,
you seem to have 3 values for `Sample` and 3 values for `phase` in your dataset. The warning occurs because there are cells with multiple possible `phase` values for each `Sample` value (e.g. G2M, G2 and S for HT4). If you only use `Sample` as your sample identifier, scCODA will try to create 3 samples (HT4, HT2, HT1), but it's unclear which value of `phase` should be assigned to each sample.
Therefore (assuming that each combination of conditions has only one replicate) you should use both `Sample` and `phase` as your sample identifier (passing them as a list).

**Comment by kvshams** [comment]
@johannesostner Thank you for the explanation. It works like a charm!

**Comment by Zethson** [comment]
@johannesostner I have the impression that we might need to improve the documentation here a bit? Would you be interested in filing up a PR for this? Else I can try to have a stab at it later

**Comment by johannesostner** [comment]
I can try to improve the documentation on this. Guess that a few examples/short explanation will help a lot there
