### ISSUE TITLE
"Unknown environment 'tabular'" error in some tutorials

### ISSUE THREAD

**Issue by VladimirShitov** [theislab/pertpy#255]
### Report

Reading the [page](https://pertpy.readthedocs.io/en/latest/tutorials/notebooks/sccoda.html) with sccoda tutorial, I noted that some illustrations (probably, with tables) are broken:
<img width="769" alt="image" src="https://user-images.githubusercontent.com/35199218/235682356-73a5f0ff-de51-4097-9bd6-a3602974d18a.png">

I didn't check other tutorials but they might suffer from the same problem. Probably, something is wrong with documentation rendering engine

**Comment by Zethson** [comment]
Potentially due to https://github.com/mathjax/mathjax-docs/wiki/LaTeX-Tabular-environment

**Comment by Zethson** [comment]
Fixed https://github.com/theislab/pertpy/commit/7a2f8233d934b730a5605c8c53fdc65392992984
