### ISSUE TITLE
LLVM ERROR: can not load pertpy with rpy2 environment

### ISSUE THREAD

**Issue by kvshams** [theislab/pertpy#261]
### Report

I am getting an error in loading `pertpy` as follows
```
>>> import pertpy as pt
LLVM ERROR: Symbol not found: __svml_sqrtf8

Aborted (core dumped)
```
If I am creating a conda environemnt without `rpy2` it works well and can use most of the modules that does not depend an R package like `Augur`. Is this a bug. I tried few fix that is recomented for [cellpose](https://github.com/MouseLand/cellpose/issues/432) and other [umap](https://github.com/lmcinnes/umap/issues/702) packages and did not fix the issue. `rpy2` seems to be working well
```
 print(robjects.r('R.version.string'))
[1] "R version 4.2.3 (2023-03-15)"
```

### Version information

 
```
>>> session_info.show(html=False, dependencies=True)
-----
scanpy              1.9.3
session_info        1.0.0
-----
PIL                 9.5.0
anndata             0.9.1
cffi                1.15.1
cycler              0.10.0
cython_runtime      NA
dateutil            2.8.2
defusedxml          0.7.1
google              NA
h5py                3.8.0
igraph              0.10.4
importlib_metadata  NA
importlib_resources NA
joblib              1.2.0
kiwisolver          1.4.4
leidenalg           0.9.1
llvmlite            0.39.1
matplotlib          3.7.1
mpl_toolkits        NA
mpmath              1.3.0
natsort             8.3.1
numba               0.56.4
numpy               1.23.5
nvfuser             NA
opt_einsum          v3.3.0
packaging           23.1
pandas              2.0.0
psutil              5.9.5
pyparsing           3.0.9
pytz                2023.3
scipy               1.10.1
setuptools          67.7.2
six                 1.16.0
sklearn             1.2.2
sympy               1.12
texttable           1.6.7
threadpoolctl       3.1.0
torch               2.0.1+cu117
tqdm                4.65.0
typing_extensions   NA
wcwidth             0.2.6
yaml                6.0
zipp                NA
zoneinfo            NA
-----
Python 3.9.16 | packaged by conda-forge | (main, Feb  1 2023, 21:39:03) [GCC 11.3.0]
Linux-3.10.0-1160.6.1.el7.x86_64-x86_64-with-glibc2.17
-----
Session information updated at 2023-05-12 16:44


```

**Comment by Zethson** [comment]
Thank you very much for reporting this. This is probably an upstream issue of numba and I might not be able to do anything about it. I'll keep it open though and think about it.

Thanks for using pertpy!

**Comment by kvshams** [comment]
@Zethson I found that the R path may be the issue. I was also having R loaded from default installation in the compute env (using `module load R`). When I deactivate the default R (using `module unload R`) `pertpy` loads without any issue. ie, a temporary work around for those face this issue at this point may be, having R inside the conda env and deactivate any other R installation while using `pertpy`.

**Comment by Zethson** [comment]
Great, thank you very much!
