### ISSUE TITLE
gpu not detectable

### ISSUE THREAD

**Issue by hai178912522** [theislab/pertpy#262]
I am using Ubuntu 22.04 system. When I was installing pertpy, even though my server has a graphics card installed, pertpy couldn't detect it.
Can you please package and send me the configuration file of this environment? I keep encountering installation failures.
![4f58b546eeed90bef8cef85b45929a6](https://github.com/theislab/single-cell-best-practices/assets/59815858/3986b0f6-2930-453a-94f3-20163f079f21)

**Comment by Zethson** [comment]
This could also be a Jax issue. Can you detect your GPU with Jax?

**Comment by hai178912522** [comment]
![image](https://github.com/theislab/pertpy/assets/59815858/1358a7cb-bd77-4e68-a305-46c0de5f4eba)

Yes. JAX cannot detect the GPU, but PyTorch can.

**Comment by hai178912522** [comment]
Please provide me with some additional information about my servers. Kindly assist in checking.
![image](https://github.com/theislab/pertpy/assets/59815858/ad5bea06-b93f-4bdb-badd-19a4e47cf522)

**Comment by Zethson** [comment]
I fear that this is not an issue of pertpy but something that you have to sort out with Jax.

**Comment by shihsama** [comment]
> Please provide me with some additional information about my servers. Kindly assist in checking. ![image](https://github.com/theislab/pertpy/assets/59815858/ad5bea06-b93f-4bdb-badd-19a4e47cf522)

You should install jax of CUDA version,e.g., jax[cuda12]. 
Honestly, I had tested run_nuts in CODA with GPU but this seemed to be slower than running with CPU. I have no idea.
