### ISSUE TITLE
scCODA vs Pertpy

### ISSUE THREAD

**Issue by connerlambden** [theislab/pertpy#274]
### Report

Hi, I'm curious what the difference is between scCODA and pertpy. Is scCODA being updated anymore? Thanks!

**Comment by Zethson** [comment]
Hey,

scCODA is not maintained anymore and a new implementation in Jax has been implemented by @johannesostner (original developer of scCODA). pertpy's implementation is also approved by Maren Büttner, the lead author of scCODA. This is the official successor.
