### ISSUE TITLE
Attribute Error: module "pertpy" has no attribute 'data'

### ISSUE THREAD

**Issue by ngvananh2508** [theislab/pertpy#283]
When I ran this code, it appeared this error:
import pertpy as pt

adata = pt.data.kang_2018()

it appeared this issue: Attribute Error: module "pertpy" has no attribute 'data'.

**Comment by ngvananh2508** [comment]
I changed data to dt, and it worked.

Thank you

**Comment by Zethson** [comment]
Sorry, I'll ensure that it's `dt` everywhere in the examples etc. Where did you still see `data`?

**Comment by Zethson** [comment]
"I read the docs of pertpy and they instructed to run this code: pertpy.data.kang_2018()."

This is the part that I'm interested in. Where did you see this? 

Thanks!

**Comment by ngvananh2508** [comment]
<img width="1280" alt="image" src="https://github.com/theislab/pertpy/assets/130348585/a96ab2ca-e077-40e3-8d15-3f9293e1903b">

Here.

**Comment by Zethson** [comment]
I see.

```
import pertpy as pt

adata = pt.data.kang_2018()
```

Does however also work for me. I'm confused.

**Comment by ngvananh2508** [comment]
I am not in the lab now. Tomorrow, I will try it again and let you know. Btw, can you please fix the compatibility problem of sc_toolbox and python 3.10?

**Comment by Zethson** [comment]
Yup, I will. Thanks!

**Comment by ngvananh2508** [comment]
Thank you!

**Comment by ngvananh2508** [comment]
> I see.
> 
> ```
> import pertpy as pt
> 
> adata = pt.data.kang_2018()
> ```
> 
> Does however also work for me. I'm confused.

I have just tried the data module and it works again. I dont know what happened exactly with it.
