### ISSUE TITLE
pertpy_scCODA for scATAC-dataset?

### ISSUE THREAD

**Issue by ronghai-li** [theislab/pertpy#285]
### Description of feature

hey,thanks your all do for this beautiful package!

i am a beginner,i have some scATAC-dataset from difference groups,
i want to try to do celltype Compositional analysis use scCODA;

1.I want to know if pertpy_scCODA can use for  scATAC-dataset;

2.and how Translating from ArchR proj to Anndata,it is better if you can give a sample;

thanks all

**Comment by Zethson** [comment]
Hi,

1. If you have labeled clusters - yes. I don't see why not.
2. This is the concern of ArchR people. Please ask your question there.

Cheers

**Comment by johannesostner** [comment]
Yes, scCODA is suitable for all kinds of high-throuput sequencing data. I don't see a reason why you shouldn't use it for scATAC data, as long as you have some clustering labels. 
scATAC also has limited library size, so the data characteristics we addressed with scCODA should remain.
