### ISSUE TITLE
Attrribute error: module 'pertpy.tools' has no attribute 'Sccoda'

### ISSUE THREAD

**Issue by ngvananh2508** [theislab/pertpy#287]
### Report

When I created sccoda model, it appeared this error: AttributeError: module 'pertpy.tools' has no attribute 'Sccoda'.

Thank you for helping me!

### Version information

Pertpy version 0.4.0

**Comment by Zethson** [comment]
Can you run `import pertpy as pt`?

What's the output of `dir(pt)` then?

**Comment by Zethson** [comment]
Now `dir(pt.tl)`?

**Comment by ngvananh2508** [comment]
![image](https://github.com/theislab/pertpy/assets/130348585/3b4d8baa-cd10-449e-ac32-178ef27e361d)

**Comment by Zethson** [comment]
All tools are there except sccoda. How did that happen?

Can you import pertpy again in a new kernel and run this again? Did the installation complete without errors?

**Comment by ngvananh2508** [comment]
I tried to install pertpy again via pip and it appeared the error related to version of protobuf, then I updated protobuf. When I reinstalled pertpy again, there was not any error. I ran dir(pt.tl) again and it gave the same result.

**Comment by ngvananh2508** [comment]
The error related to compatibilty between tensorflow and protobuf.

**Comment by ngvananh2508** [comment]
I solved it by installing ete3.
