### ISSUE TITLE
Adding acceptance rate to pertpy 0.4.0

### ISSUE THREAD

**Issue by ngvananh2508** [theislab/pertpy#289]
### Description of feature

Could you please add the acceptance rate on the result pertpy.tools.Sccoda.run_nuts() in pertpy 0.4.0?

![image](https://github.com/theislab/pertpy/assets/130348585/ab7a13d5-6604-4f03-aa03-cf1b84c62ecd)

**Comment by ngvananh2508** [comment]
![image](https://github.com/theislab/pertpy/assets/130348585/f6fdb581-b0fd-479e-9e59-7f304e33a620)
Here. Adding to value of acceptance rate like that.

**Comment by Zethson** [comment]
I think that this is a numpyro thing.
