### ISSUE TITLE
AttributeError: 'DataFrame' object has no attribute 'append'

### ISSUE THREAD

**Issue by ngvananh2508** [theislab/pertpy#290]
### Report

When I run this code :

pt.pl.coda.effects_barplot(sccoda_data, "coda", "condition")
plt.show()

It raised this error.

![image](https://github.com/theislab/pertpy/assets/130348585/5ea50f55-85f2-4977-94d8-ac238b6860bc)
 
I am using pertpy 0.4.0, pandas 2.0.0.

Thank you so much for assisting me!

**Comment by Zethson** [comment]
Where you running the tutorial or what were you doing? Please always give us foolproof instructions to be able to reproduce your problem.

Thank you!

**Comment by ngvananh2508** [comment]
I am sorry, I will be more careful in the future. I am practicing the compositional analysis chapter.

**Comment by ngvananh2508** [comment]
I read in https://stackoverflow.com/questions/75956209/dataframe-object-has-no-attribute-append, "append" method was removed so we can not use "append" method in pandas 2.0.0 anymore.

**Comment by Zethson** [comment]
We'll look into it! You can probably downgrade Pandas then temporarily to fix it.

**Comment by ngvananh2508** [comment]
I got it. Thank you!

**Comment by Zethson** [comment]
Fixed in the next release.
