### ISSUE TITLE
ete3 import error

### ISSUE THREAD

**Issue by liuifrec** [theislab/pertpy#309]
### Report

When trying to reproduce the result of the compositional notebook from the single-cell-best-practices
I keep bumping into the error not able to import the pt.pl.coda. 
Tried reinstall with pertpy 0.3.0 and 0.4.0, there seems to be the same problem.
If I remove the try and except:
try:
    from pertpy.plot._coda import CodaPlot as coda  # noqa: N813
except ImportError:
    pass
in the 
___init___.py
of the plot and force it to import the CodaPlot class, I will bump into the:
 
ImportError: cannot import name 'CircleFace' from 'ete3' 

error

**Comment by Zethson** [comment]
Did you install ete3?

**Comment by liuifrec** [comment]
Tried installed ete3 with Mamba, conda and pip in python 3.9 enviroment. It worked with the legacy scCODA viz functions, but I can't find why the ete3 not recognize the CircleFace and other classes import. Checked the ete3 github page, and it seems to have something to do with the pytqt 4 and 5 conflicts?

**Comment by Zethson** [comment]
Yeah, that's possible. You will need to provide more information

**Comment by liuifrec** [comment]
[package_list.txt](https://github.com/theislab/pertpy/files/11973779/package_list.txt)
Hi! Sorry for the lack of information. 
I just uploaded a list of packages generated through conda list in the enviroment:

ete3                      3.1.3                    pypi_0    pypi

ete3 3.1.3 was installed through pypi

**Comment by Zethson** [comment]
Did you use a fresh venv and what OS?

**Comment by Zethson** [comment]
Closing due to lack of information. Feel free to comment again and I'll reopen.
