### ISSUE TITLE
Probably wrong name of example dataset in Distances tutorial

### ISSUE THREAD

**Issue by eroell** [theislab/pertpy#384]
### Report

**Description**
In the [Distances Tutorial Notebook](https://pertpy.readthedocs.io/en/latest/tutorials/notebooks/distances.html), the used example dataset `pt.dt.example_dataset()` is not available:

**Observed behaviour**
`adata = pt.dt.distance_example_data()`

raises

`AttributeError: module 'pertpy.data' has no attribute 'distance_example_data'`

from the data module, it appears the correct name is `distance_example`, so the line should be probably

**Suggested fix**
`adata = pt.dt.distance_example()`

If the dataset has changed together with the name, maybe there'd be more to consider, not sure about that.

**Related Session Info**
`pertpy 0.6.0`

**Comment by Zethson** [comment]
Sorry. Fixed! May or may not render on the docs soon but you already figured it out :)
