### ISSUE TITLE
cannot import sccoda with reticulate

### ISSUE THREAD

**Issue by adityamahadevaniyer** [theislab/pertpy#402]
**Question**

sccoda_model = pertpy.tl.Sccoda()
Unable to access the model from pertpy despite installing various versions

I’m trying to replicate differential abundance analysis from the tutorial.

**Comment by Zethson** [comment]
Hi,

can you please add more information? Which Python version, which OS etc? Can you import pertpy without sccoda?

What do you get when you

```python
import pertpy
```

**Comment by adityamahadevaniyer** [comment]
Sure . I am running the code on Rstudio server that’s based on Linux system using reticulate. 
Python version 3.9
When I run import pertpy, I do not get any error(s). 
I installed pertpy using py_install(“pertpy”, pip = TRUE)

**Comment by adityamahadevaniyer** [comment]
![IMG_0360](https://github.com/theislab/pertpy/assets/75329396/600cf9a0-e40c-4e7e-bd2d-c085872e17bd)

**Comment by Zethson** [comment]
Does it work if you install and import it outside reticulate?

**Comment by adityamahadevaniyer** [comment]
I tried it in Google colab . It’s not working there . https://colab.research.google.com/drive/1j7sNwzZ2YT1PmnmmYC2T_7Rm_Jd0wFJW?usp=sharing

**Comment by adityamahadevaniyer** [comment]
I also tried installing pertpy using conda. Able to access tl in jupyter notebook but no Sccoda module available. 
![IMG_6033](https://github.com/theislab/pertpy/assets/75329396/4018c183-7074-4bda-98af-9b748777a9ed)

**Comment by Zethson** [comment]
It is sadly known currently that it does not work on google colab. Sorry about that.

Which operating system are you using?

**Comment by adityamahadevaniyer** [comment]
thanks for the response. I am currently using Ubuntu Release 20.04 in the case of the jupyter notebook .

Rstudio version for reticulate R.3.0

**Comment by Zethson** [comment]
I am really surprised.

On your Ubuntu system, does

1. `conda create -n pertpy python=3.11`
2. `conda activate pertpy`
3. `pip install pertpy`
4. Importing pertpy and attempting to access scoda

Not work? Could you please confirm this?

**Comment by adityamahadevaniyer** [comment]
Thanks. When I run **pip install pertpy** after following the instructions given above 
![IMG_0363](https://github.com/theislab/pertpy/assets/75329396/b79d5180-d60e-495c-a4f7-00bb0cc920ad)
