### ISSUE TITLE
Consistent API experience

### ISSUE THREAD

**Issue by Zethson** [theislab/pertpy#405]
### Description of feature

We should ensure that the API is as consistent as possible. Basically, switching from one tool to another should feel like you can already guess the API - simply familiar.

We attempted to achieve that in a couple of ways:

1. We're creating an object of every tool
2. Using `tl` and `pl` like scanpy
3. We were striving to always have a `load` function if we need to prepare AnnData objects

Things to investigate:
1. I am not confident that we always have `load` functions for every tool (are they named like this? Do they do what they're supposed to do - preparing an AnnData object?). 
2. The `Distance` class behaves a bit differently. Is there an easy/nice way to make it behave similar? Should we?
3. Metadata stuff?
4. Any other ideas to make the API more consistent?

Taks:

- [x] Investigate the whole API and report back here
- [x] Propose solutions/implementations
- [x] Implement them in pertpy
- [x] Update pertpy-tutorials

**Comment by Lilly-May** [comment]
| Tool | load() present|
| -------- | ---------- |
| Mixscape | 🚫 |
| Milo | ✅ |
| scCODA  | ✅ |
| tascCODA | ✅ |
| Dialogue | ✅ |
| Distance    | 🚫 |
| DistanceTest | 🚫 |
| CellLineMetaData | 🚫 |
| Augur | ✅ |
| SCGEN | ✅ |
| Cinemaot | 🚫 |
| DiscriminatorClassifierSpace | ✅ |
| CentroidSpace | 🚫 |
| DBSCANSpace | 🚫 |
| KMeansSpace | 🚫 |
| PseudobulkSpace | 🚫 |

**Comment by Lilly-May** [comment]
In order to make the functionality of the Distance class more consistent, one could consider moving basically everything in the `call` method into a `compute` method.

Hence, instead of:
```
adata = pt.dt.distance_example()
Distance = pt.tools.Distance(metric="edistance")
X,Y = adata.obsm[...], adata.obsm[..]
distance = Distance(X, Y)
```

We would have:
```
adata = pt.dt.distance_example()
Distance = pt.tools.Distance(metric="edistance")
X,Y = adata.obsm[...], adata.obsm[..]
distance = Distance.compute(X, Y)
```

**Comment by Lilly-May** [comment]
I think those are all ideas I have to make the API more consistent. @Zethson, could you maybe have a look and tell me what you think about these suggestions?
Thanks in advance!

**Comment by Zethson** [comment]
This is really really cool! Thank you very much.

1. Your TODO list looks great.
2. I'm not sure whether we should rename the SCGen stuff because we're using terminology and API design here from scvi-tools where these functions are named the way we're naming them
3. Let's talk about `Distance` some more. See other issue + Slack.

**Comment by Lilly-May** [comment]
If we don't want to rename the scGen stuff, I believe we can close this issue. All the other ToDos are merged and we have an extra issue for the Distance API. What do you think @Zethson?

**Comment by Zethson** [comment]
Yup! Amazing work, thank you
