### ISSUE TITLE
Speedup base coda load

### ISSUE THREAD

**Issue by Zethson** [theislab/pertpy#438]
### Description of feature

We noticed that the `load` function of scCODA is really slow:

It calls 'from_scanpy`: https://github.com/theislab/pertpy/blob/main/pertpy/tools/_coda/_base_coda.py#L1446

- [ ] Use a profiler aka tuna to figure out what is slow. Edit the issue with more things that we can find.
- [ ] It's probably https://github.com/theislab/pertpy/blob/main/pertpy/tools/_coda/_base_coda.py#L1503 where the groupby is repeatedly performed. Move it outside the for loop
- [ ] https://github.com/theislab/pertpy/blob/main/pertpy/tools/_coda/_base_coda.py#L1477C55-L1477C82 should probably be a set operation

**Comment by yugeji** [comment]
Running on a dataset with 844 experimental samples currently takes ~10min. Moving the groupby out of the for loop unfortunately only reduced this to 5min 22s.

**Comment by kcArtemis** [comment]
Hey @yugeji ,
Please can you share what data have you used? 
I want to test the speed on that data, so it would be really helpful if you can give some reference for that data.
