### ISSUE TITLE
Augur breaks with certain versions

### ISSUE THREAD

**Issue by yugeji** [theislab/pertpy#449]
### Report

scanpy==1.9.6 anndata==0.10.3 umap==0.5.5 numpy==1.26.2 scipy==1.11.4 pandas==2.1.3 scikit-learn==1.3.2 statsmodels==0.14.0 igraph==0.10.8 pynndescent==0.5.11

and pertpy 0.6.0

Outdated numpy call in statsmodels when importing from _augur.py (sorry didn't get the exact error). Fixed by downgrading to numpy 1.23.5 - consider pinning whatever statsmodels pins?

**Comment by Zethson** [comment]
Thanks! I'll look into this

**Comment by Zethson** [comment]
BYE
