### ISSUE TITLE
Consistent API: Dialogue's load method

### ISSUE THREAD

**Issue by Lilly-May** [theislab/pertpy#463]
### Description of feature

`sc.tl.Dialogue` has a method `load`. Here's the docs description of what it does:

> Separates cell into AnnDatas by celltype_key and creates the multifactor PMD input.
> Mimics DIALOGUE's `make.cell.types` and the pre-processing that occurs in DIALOGUE1.

As we typically name the methods responsible for preparing the AnnData objects `load`, I find this method's name somewhat confusing.

Firstly, I am uncertain whether this method needs to be public. It is used internally by `calculate_multifactor_PMD`, is there a scenario where users would need to employ it directly? If not, we could consider making it protected.

Another option is renaming it to `make_cell_types`. Although it does work with the AnnData, in my opinion it doesn't really prepare it for downstream processing as one would expect from the method's name. For instance, the user doesn't need to call the method before using another dialogue method.

**Comment by Zethson** [comment]
We can make it protected I think. Thank you!
