### ISSUE TITLE
Discriminator classifier throws errors due to mismatched neural network dimensions

### ISSUE THREAD

**Issue by Lilly-May** [theislab/pertpy#468]
### Report

I'm encountering errors when training the DiscriminatorClassifierSpace. When loading the classifier with batch normalization, I receive the following `RuntimeError: running_mean should contain 1 element, not 512`. Without batch normalization, this error disappears, but instead I get another `RuntimeError: Expected target size [256, 26], got [256] instead`.

These issues exist for me for both the papalexi and Norman datasets. I think resolving these bugs should be fairly easy by fixing the dimensions of the NN layers. However, I would like to confirm that these errors are not just due to my setup.

The errors should appear e.g. when doing the following:

```
adata = pt.dt.papalexi_2021()['rna']
sc.pp.normalize_total(adata)
sc.pp.log1p(adata)
sc.pp.highly_variable_genes(adata, subset=True)
ps = pt.tl.DiscriminatorClassifierSpace()
classifier_ps = ps.load(adata, target_col="gene_target", hidden_dim=[512, 256], dropout=0.05)
classifier_ps.train(max_epochs=20)
```

**Comment by Zethson** [comment]
Running into the former error message so yeah - confirmed
