### ISSUE TITLE
DIALOGUE implementation completeness?

### ISSUE THREAD

**Issue by pakiessling** [theislab/pertpy#522]
Hi all,

impressive work!

I am very interested in the python implementation of DIALOGUE.

Do you think this is in a state where I can use it for an important project, or do you recommend me to stick to the original for the time being?

Thanks!

**Comment by yugeji** [comment]
Hi pakiessling,

Thanks so much for your interest in our work! Unfortunately, the pertpy implementation of DIALOGUE is partially incomplete at the moment: you can see that in our tutorial notebook, the extraction of significant genes is not the same as in the original, and we also don't have the PhenoZ score implemented.

However, the extraction of significant genes is considerably faster with the HLM of the original, and I never could get PhenoZ scores to work in R, personally. So, if these latter steps in the pipeline are of less importance to you vs. setting up an R environment, I can say that you can feel confident that the MCP scores assigned in pertpy are extremely close to those in the R implementation. Additionally, we provide an experimental solver that disregards the order in which the cell types are passed, which is _not_ a feature of the original implementation (see https://github.com/livnatje/DIALOGUE/issues/29).

Overall, I would still recommend trying the original implementation, and barring being able to get that to work, switch to the pertpy implementation.

Thanks for your patience!

**Comment by pakiessling** [comment]
Thank you for your detailled reply!
