### ISSUE TITLE
Augur results have different dictionary dimensions

### ISSUE THREAD

**Issue by namsaraeva** [theislab/pertpy#534]
### Report

While running the Augur example code

```
import pertpy as pt
adata = pt.dt.bhattacherjee()
ag_rfc = pt.tl.Augur("random_forest_classifier")

data_15 = ag_rfc.load(adata, condition_label="Maintenance_Cocaine", treatment_label="withdraw_15d_Cocaine")
adata_15, results_15 = ag_rfc.predict(data_15, random_state=None, n_threads=4)
adata_15_permute, results_15_permute = ag_rfc.predict(data_15, augur_mode="permute", n_subsamples=100, random_state=None, n_threads=4)

data_48 = ag_rfc.load(adata, condition_label="Maintenance_Cocaine", treatment_label="withdraw_48h_Cocaine")
adata_48, results_48 = ag_rfc.predict(data_48, random_state=None, n_threads=4)
adata_48_permute, results_48_permute = ag_rfc.predict(data_48, augur_mode="permute", n_subsamples=100, random_state=None, n_threads=4)
pvals = ag_rfc.predict_differential_prioritization(augur_results1=results_15, augur_results2=results_48, permuted_results1=results_15_permute, permuted_results2=results_48_permute)
```

 I stumbled upon different dimensions of results:

![grafik](https://github.com/theislab/pertpy/assets/99650244/6548eeab-853c-486e-aff5-cc844b461996)

![grafik](https://github.com/theislab/pertpy/assets/99650244/e72c325f-bad5-4bbd-82dc-bbad785a91c1)

For some weird reason, permuted 48h results lose the `NF Oligo` dictionary.

This needs further investigation.

**Comment by namsaraeva** [comment]
I ran the code again and apparently there was a reason for this behaviour. Logging message when running `adata_48_permute, results_48_permute = ag_rfc.predict(data_48, augur_mode="permute", n_subsamples=100, random_state=None, n_threads=4)` says:

`Skipping NF Oligo cell type - 79 samples is less than min_cells 100.` 

@Zethson do we keep it as it is?

**Comment by Zethson** [comment]
Then yes
