### ISSUE TITLE
encounting issues when running DIALOGUE

### ISSUE THREAD

**Issue by SNOL2** [theislab/pertpy#568]
### Report

Hi, thanks for devloping this fantastic framework! I encounted an error when running dl.calculate_multifactor_PMD. Output are detailed below:
![image](https://github.com/theislab/pertpy/assets/116245252/007a428b-187f-4ebb-885e-393952efb927)

### Version information

-----
anndata             0.10.3
pandas              2.1.3
pertpy              0.6.0
scanpy              1.9.6
scipy               1.11.4
session_info        1.0.0
-----
Cython                      3.0.6
PIL                         10.0.1
absl                        NA
adjustText                  0.8
aiohttp                     3.9.1
aiosignal                   1.3.1
annotated_types             0.6.0
anyio                       NA
arrow                       1.3.0
arviz                       0.17.0
asttokens                   NA
async_timeout               4.0.3
attr                        23.1.0
attrs                       23.1.0
babel                       2.13.1
backoff                     2.2.1
bokeh                       3.3.1
brotli                      1.1.0
bs4                         4.12.2
certifi                     2023.11.17
cffi                        1.16.0
chardet                     5.2.0
charset_normalizer          3.3.2
chex                        0.1.7
click                       8.1.7
cloudpickle                 3.0.0
colorama                    0.4.6
comm                        0.1.4
contextlib2                 NA
croniter                    NA
cycler                      0.12.1
cython                      3.0.6
cython_runtime              NA
cytoolz                     0.12.2
dask                        2023.11.0
dateutil                    2.8.2
debugpy                     1.8.0
decorator                   5.1.1
decoupler                   1.5.1
deepdiff                    6.7.1
defusedxml                  0.7.1
dill                        0.3.7
docrep                      0.3.2
etils                       1.6.0
exceptiongroup              1.2.0
executing                   2.0.1
fastapi                     0.108.0
fastjsonschema              NA
flax                        0.7.5
fqdn                        NA
frozenlist                  1.4.0
fsspec                      2023.9.2
gmpy2                       2.1.2
h5py                        3.9.0
idna                        3.6
igraph                      0.10.4
importlib_metadata          NA
importlib_resources         NA
ipykernel                   6.26.0
ipywidgets                  8.1.1
isoduration                 NA
jax                         0.4.23
jaxlib                      0.4.23
jaxopt                      NA
jedi                        0.19.1
jinja2                      3.1.2
joblib                      1.3.2
json5                       NA
jsonpointer                 2.4
jsonschema                  4.20.0
jsonschema_specifications   NA
jupyter_events              0.9.0
jupyter_server              2.11.1
jupyterlab_server           2.25.2
kiwisolver                  1.4.5
leidenalg                   0.9.1
lightning                   2.0.9.post0
lightning_cloud             0.5.57
lightning_fabric            2.1.3
lightning_utilities         0.10.0
llvmlite                    0.41.1
lxml                        4.9.3
lz4                         4.3.2
markupsafe                  2.1.3
matplotlib                  3.7.2
matplotlib_inline           0.1.6
mizani                      0.9.3
ml_collections              NA
ml_dtypes                   0.3.1
mpl_toolkits                NA
mpmath                      1.3.0
msgpack                     1.0.7
mudata                      0.2.3
multidict                   6.0.4
multipart                   0.0.6
multipledispatch            0.6.0
natsort                     8.4.0
nbformat                    5.9.2
numba                       0.58.1
numexpr                     2.8.7
numpy                       1.24.4
numpyro                     0.13.2
opt_einsum                  v3.3.0
optax                       0.1.7
ordered_set                 4.1.0
ott                         0.4.4
overrides                   NA
packaging                   23.2
parso                       0.8.3
patsy                       0.5.3
pexpect                     4.8.0
pickleshare                 0.7.5
pkg_resources               NA
platformdirs                4.0.0
plotnine                    0.12.4
ply                         3.11
prometheus_client           NA
prompt_toolkit              3.0.41
psutil                      5.9.5
ptyprocess                  0.7.0
pure_eval                   0.2.2
pyarrow                     14.0.1
pycparser                   2.21
pydantic                    2.1.1
pydantic_core               2.4.0
pydev_ipython               NA
pydevconsole                NA
pydevd                      2.9.5
pydevd_file_utils           NA
pydevd_plugins              NA
pydevd_tracing              NA
pygments                    2.17.2
pyomo                       6.7.0
pyparsing                   3.0.9
pyro                        1.8.6
pythonjsonlogger            NA
pytorch_lightning           2.1.3
pytz                        2023.3.post1
referencing                 NA
requests                    2.31.0
rfc3339_validator           0.1.4
rfc3986_validator           0.1.1
rich                        NA
rpds                        NA
scvi                        1.0.4
seaborn                     0.12.2
send2trash                  NA
six                         1.16.0
sklearn                     1.3.2
skmisc                      0.3.1
sniffio                     1.3.0
socks                       1.7.1
soupsieve                   2.5
sparse                      0.14.0
sparsecca                   0.3.1
stack_data                  0.6.2
starlette                   0.32.0.post1
statsmodels                 0.14.0
sympy                       1.11.1
tblib                       3.0.0
texttable                   1.7.0
threadpoolctl               3.2.0
tlz                         0.12.2
tomli                       2.0.1
toolz                       0.12.0
torch                       2.1.0
torchgen                    NA
torchmetrics                1.2.1
tornado                     6.3.3
tqdm                        4.66.1
traitlets                   5.14.0
tree                        0.1.8
typing_extensions           NA
uri_template                NA
urllib3                     2.0.7
uvicorn                     0.25.0
wcwidth                     0.2.12
webcolors                   1.13
websocket                   1.6.4
websockets                  12.0
wrapt                       1.16.0
xarray                      2023.11.0
xarray_einstats             0.6.0
xyzservices                 2023.10.1
yaml                        6.0.1
yarl                        1.9.3
zipp                        NA
zmq                         25.1.1
zoneinfo                    NA
zstandard                   0.22.0
-----
IPython             8.18.1
jupyter_client      8.6.0
jupyter_core        5.5.0
jupyterlab          4.0.9
-----
Python 3.10.13 | packaged by conda-forge | (main, Oct 26 2023, 18:07:37) [GCC 12.3.0]
Linux-5.4.0-150-generic-x86_64-with-glibc2.28
-----
Session information updated at 2024-03-24 21:56

**Comment by Zethson** [comment]
@SNOL2 could you please document here how you fixed your issue?

**Comment by Zethson** [comment]
No worries! We should ensure that a more informative error is thrown. Thanks!
