### ISSUE TITLE
Can not import pertpy

### ISSUE THREAD

**Issue by SimonE1220** [theislab/pertpy#584]
### Report

If i import the pertpy, this error appears

ImportError                               Traceback (most recent call last)
[<ipython-input-8-1046a64f3724>](https://localhost:8080/#) in <cell line: 1>()
----> 1 import pertpy as pt
      2 import scanpy as sc

3 frames
[/usr/local/lib/python3.10/dist-packages/pertpy/tools/_coda/_sccoda.py](https://localhost:8080/#) in <module>
     10 from anndata import AnnData
     11 from jax import random
---> 12 from jax.config import config
     13 from mudata import MuData
     14 from numpyro.infer import Predictive

ImportError: cannot import name 'config' from 'jax.config' (/usr/local/lib/python3.10/dist-packages/jax/config.py)

**Comment by Zethson** [comment]
You can install from main. We'll make a new release this weekend! Sorry for the inconvenience...

Apr 12, 2024 4:09:55 PM SimonE1220 ***@***.***>:
