### ISSUE TITLE
How to use Pertpy after subsetting the cell types?

### ISSUE THREAD

**Issue by mainharryHR** [theislab/pertpy#600]
### Description of feature

Dear Sir or Madam,
Thank you all for the great package. I did single cell sequencing for whole tissue: Epitheliums, Stromal cells, and Immune cells. For my analysis, I subset the data into above 3 sub-groups and then did the annotations and other analysis separately. I employed Pertpy on immune cells population. In order to discover the true phenotypes, I feel I need to consider the stromal cells and epitheliums, am I right? If so, what is the best practices for whole tissue single cells? I guess we need to merge all the sub-groups together to perform Pertpy pipeline again?
 
Thank you all!

Best,
Harry

**Comment by Zethson** [comment]
Hi,

I get your experimental setup, but the subsequent steps highly depend on what you're interested in. What are you looking for? What are your scientific questions?

**Comment by mainharryHR** [comment]
> Hi,
> 
> I get your experimental setup, but the subsequent steps highly depend on what you're interested in. What are you looking for? What are your scientific questions?

It seems you work late too. Haha.  

My questions are how different cell types are changing in cancer patients.  There are around 50 cell types in total. That is why I subset the samples into big groups.  For examples, if I want to know Treg cells are affected in cancer, I feel I need to take stromal and epitheliums into account. I guess I need to merge all sample.

I am thinking if we know the proportions of these 3 groups (stromal cells, epithelium, and immune cells) at different coditions (Healthy VS Cancer), could we input this proportion value to immune cell subgroup for Perpy analysis. Maybe this is a strategies instead of merging the sub-groups. 

Happy to discuss more. 

Best,
Harry

**Comment by Zethson** [comment]
> For examples, if I want to know Treg cells are affected in cancer, I feel I need to take stromal and epitheliums into account. I guess I need to merge all sample.

You could try to identify multicellular programs using DIALOGUE or through cell cell communication such as nichenet. See https://www.science.org/doi/full/10.1126/scitranslmed.adh0908 for an example of the latter.

Then you can examine these programs throughout your analysis.
