### ISSUE TITLE
Fixing incorrect y-axis in volcano plot

### ISSUE THREAD

**Issue by pakiessling** [theislab/pertpy#621]
### Report

Hi, I want to fix the incorrect y-axis scaling which is caused by  max_log2fc being used as y-axis maximum.

However I have not been able to execute the code in 
https://github.com/theislab/pertpy-tutorials/blob/main/differential_gene_expression.ipynb

```
----> pydeseq2.volcano(res_df, log2fc_thresh=0)

AttributeError: 'PyDESeq2' object has no attribute 'volcano'
```

Is there a specific branch I should be looking at?

Ty!

**Comment by Zethson** [comment]
Sorry, it got renamed to `plot_volcano`. I'll fix it in the example.
